# Generated by Django 2.0.4 on 2018-06-17 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=30)),
                ('date', models.CharField(choices=[('SUN', 'sunday'), ('MON', 'monday'), ('TUE', 'tuesday'), ('WED', 'wednssday'), ('THU', 'thursday')], max_length=3)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('instructor_name', models.CharField(max_length=30)),
                ('subject_grade', models.IntegerField()),
            ],
        ),
    ]
