# Generated by Django 2.0.2 on 2018-04-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='year',
            field=models.IntegerField(blank=True, choices=[(1, 'First'), (2, 'sdf'), (3, 'Fifsdfrst'), (4, 'Fisfddsfrst')], null=True),
        ),
    ]
