# Generated by Django 2.0.4 on 2018-06-17 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0002_auto_20180426_1709'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'profile', 'verbose_name_plural': 'profiles'},
        ),
    ]
